services:
  monaco-editor-lsp-next:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: monaco-editor-lsp-next
    restart: always
    ports:
      - "3000:3000"

  lsp-c:
    build:
      context: ./docker/lsp/clangd
      dockerfile: Dockerfile
    container_name: lsp-c
    restart: always
    ports:
      - "4594:3000"

  lsp-cpp:
    build:
      context: ./docker/lsp/clangd
      dockerfile: Dockerfile
    container_name: lsp-cpp
    restart: always
    ports:
      - "4595:3000"
